### ISSUE TITLE
AngularJS UI conflict

### ISSUE THREAD

**Issue by OmarIthawi** [AbdullahDiaa/Bootstrap-RTL#10]
Salam Abdullah,

`popover` of AngularUI isn't appearing correctly when combined with Bootstrap-RTL's css.

**Reproduce:**
- Use AngularJS 1.0.7
- Use AngularUI 0.7.0
- Use Bootstrap-RTL
- Create a popover

_Check the plunker codes bellow_

**Expected:** The popover to have a correct `placement` and close to the target element. 
**Actual:** The popover is too far from the target element.
## Pulnker Code 
- AbdullahDiaa-Bootstrap-RTL.css isn't working well:  [Pulnker: uURwW0](http://plnkr.co/edit/uURwW0?p=preview)
- izer0x's Bootstrap-Arabic css is working fine: [Pulnker: 9fWqpH](http://plnkr.co/edit/9fWqpH?p=preview)

**Comment by evilaliv3** [comment]
@OmarIthawi have you solved it somehow?

This bootstrap fork is surely better https://github.com/MohammadYounes/RTL-bootstrap/tree/inline-rtl but we need to patch the angular-ui tooltip.js in order to fix your issue.

have you already managed to do that?

**Comment by OmarIthawi** [comment]
@evilaliv3 I don't remember what happened with this bug. But I think I've solved it by editing the `popover.js`.
