### ISSUE TITLE
arabic bootstrap 2.3.2

### ISSUE THREAD

**Issue by zeroxme** [AbdullahDiaa/Bootstrap-RTL#6]
please have a look 
http://zerox.me/projects/bootstrap/

**Comment by neo22s** [comment]
wow thanks!

**Comment by zeroxme** [comment]
you are welcome and any contributions are welcome :)

**Comment by zeroxme** [comment]
bootstrap 3 arabic ... http://zerox.me/projects/bootstrap3/

**Comment by AbdullahDiaa** [comment]
Bootstrap 2.3.2 has been released.
