### ISSUE TITLE
Did you begin building bootstrap 3 rtl

### ISSUE THREAD

**Issue by kassemshehady** [AbdullahDiaa/Bootstrap-RTL#7]
Did you begin building bootstrap 3 rtl

**Comment by zeroxme** [comment]
bootstrap 3 arabic ... http://zerox.me/projects/bootstrap3/
bootstrap 2.3.2 arabic ... http://zerox.me/projects/bootstrap/

**Comment by AbdullahDiaa** [comment]
Yep, i've started working on bootstrap 3.0.2
